// import { Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar, { Back } from "@/components/NavBar";
import Footer from "@/components/Footer";
// import ToastWrapper from "./ToastWrapper";
import Wrapper from "./ToastWrapper";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen`}
      >
        <Wrapper>
          <NavBar />
          {/* <Back/> */}
          {children}
        </Wrapper >
        <Footer />
      </body>
    </html>
  );
}
